zaliczenie/config/routes.rb
Rails.application.routes.draw do
  resources :cards
  root 'home#index'
  
  
  
  

end

zaliczenie/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

zaliczenie/app/models/card.rb
class Card < ActiveRecord::Base
end

zaliczenie/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

zaliczenie/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
    @cards = Card.paginate(:page => params[:page], :per_page => 4)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :color, :cost, :power, :toughness)
    end
end

zaliczenie/app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
  end

end

zaliczenie/app/helpers/application_helper.rb
module ApplicationHelper
end

zaliczenie/app/helpers/cards_helper.rb
module CardsHelper
end

zaliczenie/app/views/cards/_form.html.erb
<%= simple_form_for(@card) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name, :input_html => {:maxlength =>2,:style=> 'width: 250px'}%>
    <%= f.input :color, :input_html => {:maxlength =>2,:style=> 'width: 250px'}%>
    <%= f.input :cost,  :input_html => {:maxlength =>2,:style=> 'width: 100px'}%>
    <%= f.input :power, :input_html => {:maxlength =>2,:style=> 'width: 50px'}%>
    <%= f.input :toughness, :input_html => {:maxlength =>2,:style=> 'width: 50px'}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

zaliczenie/app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

zaliczenie/app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>


<div class="table-responsive">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Cost</th>
      <th>Power</th>
      <th>Toughness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.color %></td>
        <td><%= card.cost %></td>
        <td><%= card.power %></td>
        <td><%= card.toughness %></td>
        <td><%= link_to card, class:'btn btn-primary btn-xs' do %>
        <i class='glyphicon glyphicon-eye-open'></i> Show
        <% end %>
        </td>
        <td><%= link_to edit_card_path(card), class:'btn btn-primary btn-xs' do %>
         <i class='glyphicon glyphicon-pencil'></i> Edit
        <% end %>
        </td>
        <td><%= link_to card, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-xs' do %>
          <i class='glyphicon glyphicon-trash'></i> Destroy
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

 
  <%= will_paginate @card %>
  


<br>

<%= link_to new_card_path, class: 'btn btn-success' do %>
 <i class='glyphicon glyphicon-plus'></i> New Card
<% end %>

zaliczenie/app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

zaliczenie/app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table-condensed">
<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @card.color %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @card.cost %>
</p>

<p>
  <strong>Power:</strong>
  <%= @card.power %>
</p>

<p>
  <strong>Toughness:</strong>
  <%= @card.toughness %>
</p>
</table>
<%= link_to 'Edit', edit_card_path(@card), class: 'btn btn-default btn-sm' %> |
<%= link_to 'Back', cards_path, class: 'btn btn-default btn-sm' %>

zaliczenie/app/views/home/index.html.erb
<div class="jumbotron"> 

    <div align="center">
    <h1>Cards Database</h1>
    <h2>Projekt na zaliczenie przedmiotu ASI 2016</h2>
    </div>
</div>   

zaliczenie/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Cards Database', root_path, class: 'navbar-brand' %>
    </div>
      <ul class="nav navbar-nav navbar">
        <li><%= link_to 'Cards', cards_path %></li>
      </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
    </div>
  </div>
</nav>

zaliczenie/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cards Database</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 
<body>
  
  <%= render 'layouts/navbar' %>
  
<%= yield %>

</body>
</html>